# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'events')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('venue', models.CharField(max_length=500)),
                ('venue_url', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('post_to_facebook', models.BooleanField(default=False)),
                ('posted_to_facebook', models.BooleanField(default=False)),
                ('post_to_facebook_after', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
