# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='venue_name',
        ),
    ]
