# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20170724_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='freeform_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='freeform_country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
