# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20170725_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_employee',
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(blank=True, help_text=b'Enter city here. This is used on the listings section of the website.', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.City'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_email',
            field=models.CharField(blank=True, help_text=b'Do not enter here. This is for user input from website form. Should not be made public.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.ForeignKey(help_text=b'Enter country here. This is used on the listings section of the website.', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Country'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='freeform_city',
            field=models.CharField(blank=True, help_text=b' Do not enter here. This is for user input from website form. Use city field instead.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='freeform_country',
            field=models.CharField(blank=True, help_text=b'Do not enter here. This is for user input from website form. Use country field instead.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.State'),
        ),
    ]
